# Generated by Django 5.0.1 on 2024-01-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_comment_commentlikes_post_comment_post_postlikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='comment_likes_count',
            new_name='replay_likes_count',
        ),
    ]
