# Generated by Django 5.0.1 on 2024-01-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_disease_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='therapy/'),
        ),
    ]
